version: "3.9"

services:
  client:
    ports:
      - 3000:3000
    build:
      context: client
      dockerfile: Dockerfile.client
    volumes:
      - ./client:/app/client
      - /home/app/client/node_modules
      - /app/client/.next
  server:
    ports:
      - 5000:5000
    build:
      context: server
      dockerfile: Dockerfile.server
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
